# Generated by Django 6.1.1 on 2026-09-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='user',
            new_name='author',
        ),
    ]
