# Generated by Django 6.1.1 on 2026-09-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0002_rename_user_fooditem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calorie_tracker.author'),
        ),
    ]
